version: "3.9"

services:
  web:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - .:/app
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      SQLALCHEMY_DATABASE_URI: sqlite:///blog.db 