services:
  - type: web
    name: powerdataanalytics-blog
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: alembic upgrade head
    startCommand: gunicorn app:app
    disk:
      name: uploads
      mountPath: /static/uploads
      sizeGB: 5
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: powerdatalab-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: powerdatalab-db
    databaseName: powerdatalab
    user: powerdatalab 