"""Add is_active to User model

Revision ID: 5fcc2cafc8a3
Revises: ef30ff3f1310
Create Date: 2025-05-12 11:55:03.347483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcc2cafc8a3'
down_revision: Union[str, None] = 'ef30ff3f1310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
