"""fix class Users

Revision ID: ef30ff3f1310
Revises: 28ad3cdc3d2a
Create Date: 2025-05-12 11:49:03.680944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef30ff3f1310'
down_revision: Union[str, None] = '28ad3cdc3d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page_views', 'is_bot',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.alter_column('page_views', 'is_bot',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
